---
- name: Check yay already exists
  stat:
    path: /usr/bin/yay
  register: yay_bin
  tags:
    - system
    - yay

- name: Create yay directory
  become: true
  file:
    path: /opt/yay
    state: directory
    group: users
    mode: "0775"
  when: not yay_bin.stat.exists
  tags:
    - system
    - yay

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-git.git
    dest: /opt/yay
    refspec: +refs/pull/*:refs/heads/*
    version: master
  when: not yay_bin.stat.exists
  tags:
    - system
    - yay

- name: Build and install yay
  command: makepkg -si --noconfirm
  args:
    chdir: /opt/yay
  become: false
  when: not yay_bin.stat.exists
  tags:
    - system
    - yay

- name: Update yay chache
  command: yay -Sy
  become: false
  tags:
    - system
    - yay
