---
- name: check yay already exists
  stat:
    path: "/usr/bin/yay"
  register: yay_bin
  tags:
    - system
    - yay

- name: crate yay directory
  become: yes
  file:
    path: "/opt/yay"
    state: directory
    group: "users"
    mode: 0755
  when: not yay_bin.stat.exists
  tags:
    - development
    - ide
    - intellij

- name: clone yay
  git:
    repo: "https://aur.archlinux.org/yay-git.git"
    dest: "/opt/yay"
    refspec: "+refs/pull/*:refs/heads/*"
    version: master
  when: not yay_bin.stat.exists
  tags:
    - system
    - yay

- name: Build and install yay
  command: makepkg -si --noconfirm
  args:
    chdir: /opt/yay
  when: not (yay_bin.stat.exists and ansible_user == "root")
