---
- name: check yay already exists
  stat:
    path: "/usr/bin/yay"
  register: yay_bin
  tags:
    - system
    - yay

- name: clone yay
  git:
    repo: "https://aur.archlinux.org/yay-git.git"
    dest: "/opt/yay"
    refspec: "+refs/pull/*:refs/heads/*"
    version: master
  when: not yay_bin.stat.exists
  tags:
    - system
    - yay

- name: change directory permission
  file:
    path: /opt/yay
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: users
  when: not yay_bin.stat.exists

- name: Build and install yay
  command:  makepkg -si
  args:
    chdir: /opt/yay
  when: not yay_bin.stat.exists
