---
- name: install core packages
  pacman:
    name:
      - yay
      - vim
      - meld
      - diffutils
      - unzip
      - zip
      - unrar
      - tar
      - coreutils
      - python3
      - base-devel
  become: true
  tags:
    - system

- name: Install utility tools
  package:
    name:
      - keepass
  become: true
  tags:
    - system

- name: Install web tools
  package:
    name:
      - httpie
      - firefox
      - chromium
      - mutt
  become: true
  tags:
    - system
    - network

- name: Install network tools
  package:
    name:
      - networkmanager
      - openssl
      - openvpn
      - ufw
      - gufw
      - remina
      - wireshark-qt
      - tcpdump
      - netcat-openbsd
      - iftop
  become: true
  tags:
    - system
    - network

- name: Install basic developer tools
  package:
    name:
      - git
      - tig
  become: true
  tags:
    - system
    - development
