---
- name: Install visual studio code
  pacman:
    name: code
  become: true
  tags:
    - ide

- name: Install extension
  command: /usr/bin/code --install-extension {{ item }}
  with_items:
    - golang.Go
    - redhat.vscode-yaml
    - rust-lang.rust
    - ms-python.python
    - redhat.ansible
    # TODO Install line excluder
  tags:
    - ide

- name: Link settings file from dot folder
  file:
    src: "{{ home_directory }}/repositories/dotfiles/code/user/settings.json"
    dest: "{{ home_directory }}/.config/Code - OSS/User/settings.json"
    owner: "{{ username }}"
    group: "{{ usergroup }}"
    state: link
  tags:
    - ide
    - dotfiles
