---
- name: install visual studio code
  pacman:
    name: code
  become: true
  tags:
    - ide

- name: Copy visual studio code config files
  copy:
    src: settings.json
    dest: "{{ home_directory }}/.config/Code\ -\ OSS/User/"
    force: no