---
- name: install visual studio code
  pacman:
    name: code
  become: true
  tags:
    - ide

- name: crate config directory
  become: yes
  file:
    path: "{{ home_directory }}/.config/Code\ -\ OSS/User/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "users"
    mode: 0755

- name: Copy visual studio code config files
  copy:
    src: settings.json
    dest: "{{ home_directory }}/.config/Code\ -\ OSS/User/settings.json"
    mode: 0644
    force: no