---
- name: install visual studio code
  pacman:
    name: code
  become: true
  tags:
    - ide

- name: crate config directory
  file:
    path: "~/.config/Code\ -\ OSS/User/"
    state: directory
    group: "users"
    mode: 0750

- name: Copy visual studio code config files
  copy:
    src: settings.json
    dest: "~/.config/Code\ -\ OSS/User/settings.json"
    mode: 0640
    force: no