- name: find latest version
  uri:
    url: "https://data.services.jetbrains.com/products/releases?code=IIU%2CIIC&latest=true&type=release"
    return_content: yes
    validate_certs: no
    body_format: json
  register: intellij_releases_response
  tags:
    - development
    - ide
    - intellij

- name: extract intellij version
  set_fact:
    intellij_version: "{{ intellij_releases_response.json.IIU.0.version }}"
  tags:
    - development
    - ide
    - intellij

- name: check intellij is installed
  stat:
    path: "{{ intellij_dest }}"
  register: intellij
  tags:
    - development
    - ide
    - intellij

- name: crate a directory
  become: yes
  file:
    path: "{{ intellij_dest }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ unix_group }}"
  tags:
    - development
    - ide
    - intellij
  when: not intellij.stat.exists

- name: download intellij
  unarchive:
    src: "https://download.jetbrains.com/idea/ideaIU-{{ intellij_version }}.tar.gz"
    dest: "{{ intellij_dest }}"
    mode: 0750
    remote_src: yes
  tags:
    - development
    - ide
    - intellij
  when: not intellij.stat.exists

- name: "change owner ship of intellij"
  become: yes
  file:
    path: "{{ intellij_dest }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ unix_group }}"
    mode: 0750
  tags:
    - development
    - ide
    - intellij

- name: find intellij exec file
  find:
    paths: "{{ intellij_dest }}"
    recurse: yes
    patterns: "idea.sh"
  register: intellij_exec_results
  tags:
    - development
    - ide
    - intellij

- name: find intellij png file
  find:
    paths: "{{ intellij_dest }}"
    recurse: yes
    patterns: "idea.png"
  register: intellij_png_results
  tags:
    - development
    - ide
    - intellij

- name: create idea link
  become: yes
  file:
    src: "{{ idea_exec_path }}"
    dest: /usr/bin/idea
    owner: "{{ ansible_user }}"
    group: "{{ unix_group }}"
    state: link
