---
- name: find latest version
  uri:
    url: https://data.services.jetbrains.com/products/releases?code=IIU%2CIIC&latest=true&type=release
    return_content: true
    validate_certs: false
    body_format: json
  register: intellij_releases_response
  tags:
    - development
    - ide
    - intellij

- name: extract intellij version
  set_fact:
    intellij_version: "{{ intellij_releases_response.json.IIU.0.version }}"
  tags:
    - development
    - ide
    - intellij

- name: check intellij is installed
  stat:
    path: "{{ intellij_dest }}"
  register: intellij
  tags:
    - development
    - ide
    - intellij

- name: crate a directory
  become: true
  file:
    path: "{{ intellij_dest }}"
    state: directory
    group: users
    mode: 0770
  tags:
    - development
    - ide
    - intellij
  when: not intellij.stat.exists

- name: download intellij
  unarchive:
    src: https://download.jetbrains.com/idea/ideaIU-{{ intellij_version }}.tar.gz
    dest: "{{ intellij_dest }}"
    mode: 0770
    remote_src: true
  tags:
    - development
    - ide
    - intellij
  when: not intellij.stat.exists

- name: change owner ship of intellij
  become: true
  file:
    path: "{{ intellij_dest }}"
    state: directory
    recurse: true
    mode: 0750
  tags:
    - development
    - ide
    - intellij

- name: find intellij exec file
  find:
    paths: "{{ intellij_dest }}"
    recurse: true
    patterns: idea.sh
  register: intellij_exec_results
  tags:
    - development
    - ide
    - intellij

- name: extract intellij exec path
  set_fact:
    idea_exec_path: "{{ intellij_exec_results.files[0].path }}"
  tags:
    - development
    - ide
    - intellij

- name: create idea link
  become: true
  file:
    src: "{{ idea_exec_path }}"
    dest: /usr/bin/idea
    state: link
