---
- name: install core packages
  pacman:
    name:
      - acpid
      - dbus
      - avahi
      - cups
      - bluez
      - bluez-utils
      - openssh
  become: true
  tags:
    - system

- name: Install printer driver and tools
  command: yay -S --noconfirm {{ item }}
  with_items:
    - hplip
  tags:
    - system
    - yay

- name: adding user to group sys
  user:
    name: "{{ username }}"
    groups: sys
    append: true
  become: true
  tags:
    - system
    - permission

- name: adding user to group lp
  user:
    name: "{{ username }}"
    groups: lp
    append: true
  become: true
  tags:
    - system
    - permission

- name: check if vim themes
  stat:
    path: "{{ home_directory }}/.vim/pack/themes/start"
  register: vim_theme_path
  tags:
    - system

- name: Create vim themes
  file:
    path: "{{ home_directory }}/.vim/pack/themes/start"
    state: directory
    mode: 0750
  tags:
    - system
    - dotfiles

- name: clone vim dracula
  git:
    repo: https://github.com/dracula/vim.git
    dest: "{{ home_directory }}/.vim/pack/themes/start/dracula"
    refspec: +refs/pull/*:refs/heads/*
    version: master
  when: not vim_theme_path.stat.exists
  tags:
    - system

- name: install docking station packages
  pacman:
    name:
      - bolt
  become: true
  tags:
    - system