---
- name: Install core packages
  pacman:
    name:
      - acpid
      - dbus
      - avahi
      - cups
      - bluez
      - bluez-utils
      - openssh
      - dhcpcd
  become: true
  tags:
    - system

- name: Install sound packages
  pacman:
    name:
      - pamixer
      - pulseaudio
      - pulseaudio-alsa
      - alsa-utils
      - pavucontrol
  become: true
  tags:
    - system

- name: Install printer driver and tools
  command: yay -S --needed --noconfirm {{ item }}
  with_items:
    - hplip
  tags:
    - system
    - yay

- name: Adding user to group sys
  user:
    name: "{{ username }}"
    groups: sys
    append: true
  become: true
  tags:
    - system
    - permission

- name: Adding user to group lp
  user:
    name: "{{ username }}"
    groups: lp
    append: true
  become: true
  tags:
    - system
    - permission

- name: Install docking station packages
  pacman:
    name:
      - bolt
  become: true
  tags:
    - system

- name: Install firewall tools
  package:
    name:
      - ufw
      - gufw
  become: true
  tags:
    - system
    - network
    - firewall
