---
- name: install core packages
  pacman:
    name:
      - acpid
      - dbus
      - avahi
      - cups
      - bluez
      - bluez-utils
      - openssh
  become: true
  tags:
    - system

- name: Install printer driver and tools
  community.general.pacman:
    name:
      - hplip
    state: present
    executable: yay
  tags:
    - system
    - yay

- name: adding user to group sys
  user:
    name: "{{ username }}"
    groups: sys
    append: true
  tags:
    - system

- name: adding user to group lp
  user:
    name: "{{ username }}"
    groups: lp
    append: true
  tags:
    - system
