---
- name: install core packages
  pacman:
    name:
      - acpid
      - dbus
      - avahi
      - cups
      - bluez
      - bluez-utils
      - openssh
  become: true
  tags:
    - system

- name: Install printer driver and tools
  command: yay -S --noconfirm {{ item }}
  with_items:
    - hplip
  tags:
    - system
    - yay

- name: adding user to group sys
  user:
    name: "{{ username }}"
    groups: sys
    append: true
  tags:
    - system
    - permission

- name: adding user to group lp
  user:
    name: "{{ username }}"
    groups: lp
    append: true
  tags:
    - system
    - permission
