- name: check if config directory exists
  stat:
    path: "{{ home_directory }}/configs"
  register: dot_files_directory
  tags:
    - system

- name: clone dot-files
  git:
    repo: "https://github.com/orltom/linux-user-configs"
    dest: "{{ home_directory }}/configs"
    refspec: "+refs/pull/*:refs/heads/*"
    version: master
  when: not dot_files_directory.stat.exists
  tags:
    - system

- name: Remove links
  file:
    path: "{{ home_directory }}/{{ item }}"
    state: absent
  loop:
    - .vimrc
    - .bashrc
    - .zshrc
  tags:
    - system

- name: add config links
  file:
    src: "{{ home_directory }}/configs/{{ item }}"
    dest: "{{ home_directory }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ unix_group }}"
    state: link
  loop:
    - .vimrc
    - .bashrc
    - .zshrc
    - .aliases
  tags:
    - system

- name: Create bin directory if it does not exist
  file:
    path: "{{ home_directory }}/bin"
    state: directory
    mode: 0750
  tags:
    - system

- name: add user bin command links
  file:
    src: "{{ home_directory }}/configs/bin/{{ item }}"
    dest: "{{ home_directory }}/bin/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ unix_group }}"
    state: link
  loop:
    - gitlastcommit
    - gitupdatebranch
    - change-keyboard-layout
    - screen-setup
    - show-java-imports
  tags:
    - system

- name: Create .config directory if it does not exist
  file:
    path: "{{ home_directory }}/.config"
    state: directory
    mode: 0750
  tags:
    - system

- name: add .config programm links
  file:
    src: "{{ home_directory }}/configs/.config/{{ item }}"
    dest: "{{ home_directory }}/.config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ unix_group }}"
    state: link
  loop:
    - i3
    - rofi
    - dunst
  tags:
    - system

- name: set gnome terimal without menu bar
  command: gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false
  when: not dot_files_directory.stat.exists
