---
- name: install i3
  pacman:
    name:
      - xorg
      - i3-wm
      - i3lock
      - i3status
      - xfce4-settings
      - rofi
      - dunst
  become: true

- name: install utility tools
  pacman:
    name:
    - pulseaudio
    - xfce4-settings
    - ranger
  become: true

- name: Install network tools
  become: yes
  pacman:
    name:
      - wireshark-qt
      - tcpdump
      - netcat-openbsd
      - iftop
    state: present
  tags:
    - system



