---
- name: install container software
  pacman:
    name:
    - docker
    - docker-compose
    - virtualbox
    - linux-headers
    - minikube
    - kubectl
    - helm
  become: true

- name: enable dockerd services
  become: yes
  systemd:
    name: docker.socket
    enabled: yes
    state: started

- name: Add the user to group 'docker'
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Install driver
  community.general.pacman:
    name: 
      - docker-machine-drvier-kvm2
    state: present
    executable: yay