---
- name: install container software
  become: true
  pacman:
    name:
      - docker
      - community/docker-buildx
      - docker-compose
      - virtualbox
      - linux-headers
      - kubectl
      - helm
      - jq
      - yq
      - terraform
      - terragrunt
  tags:
    - container

- name: enable dockerd services
  become: true
  systemd:
    name: docker.socket
    enabled: true
    state: started
  tags:
    - container
    - systemd

- name: Add the user to group 'docker'
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: true
  tags:
    - container
    - permission

- name: Install container software from yay
  command: yay -S --noconfirm {{ item }}
  with_items:
    - rancher-k3d-bin
    - dive-git
  tags:
    - container
    - yay
