---
- name: install container software
  pacman:
    name:
      - docker
      - docker-compose
      - virtualbox
      - linux-headers
      - minikube
      - kubectl
      - helm
  become: true

- name: enable dockerd services
  become: yes
  systemd:
    name: docker.socket
    enabled: yes
    state: started

- name: Add the user to group 'docker'
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Install driver
  community.general.pacman:
    name:
      - docker-machine-driver-kvm2
    state: present
    executable: yay

- name: Install container software from yay
  community.general.pacman:
    name:
      - origin-client
      - rancher-k3d-bin
    state: present
    executable: yay
