---
- name: install container software
  become: true
  pacman:
    name:
      - docker
      - docker-compose
      - virtualbox
      - linux-headers
      - kubectl
      - helm
      - jq
      - terraform
  tags:
    - container

- name: enable dockerd services
  become: true
  systemd:
    name: docker.socket
    enabled: true
    state: started
  tags:
    - container

- name: Add the user to group 'docker'
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: true
  tags:
    - container

- name: Install container software from yay
  community.general.pacman:
    name:
      - origin-client
      - rancher-k3d-bin
    state: present
    executable: yay
  tags:
    - container
    - yay
