---
- name: check if ZSH exists
  stat:
    path: /usr/bin/zsh
  register: zsh_path
  tags:
    - system

- name: Install zsh and extensions
  become: true
  pacman:
    name:
      - zsh
      - powerline
      - python-powerline
      - powerline-fonts
      - awesome-terminal-fonts
      - terminus-font
      - ttf-nerd-fonts-symbols
    state: present
  tags:
    - system

- name: set ZSH as default shell
  become: true
  shell: chsh -s $(which zsh)
  when: zsh_path.stat.exists
  tags:
    - system

- name: check if ohmyzsh directory exists
  stat:
    path: "{{ home_directory }}/.oh-my-zsh"
  register: ohmyzsh_directory
  tags:
    - system

# - name: Build and install font
#   command: yay -S nerd-fonts-dejavu-complete --answerclean N --answerdiff N
#   when: not ohmyzsh_directory.stat.exists
#   tags:
#     - system

- name: clone omyzsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home_directory }}/.oh-my-zsh"
    refspec: +refs/pull/*:refs/heads/*
    version: master
  when: not ohmyzsh_directory.stat.exists
  tags:
    - system

- name: clone powerline
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ home_directory }}/.oh-my-zsh/custom/themes/powerlevel9k"
    refspec: +refs/pull/*:refs/heads/*
    version: master
  when: not ohmyzsh_directory.stat.exists
  tags:
    - system

- name: clone zsh-syntax-highlighting
  git:
    repo: " https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ home_directory }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    refspec: +refs/pull/*:refs/heads/*
    version: master
  when: not ohmyzsh_directory.stat.exists
  tags:
    - system

- name: clone zsh-autosuggestions
  git:
    repo: " https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ home_directory }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    refspec: +refs/pull/*:refs/heads/*
    version: master
  when: not ohmyzsh_directory.stat.exists
  tags:
    - system
