---
- name: install i3
  pacman:
    name:
      - xorg
      - xorg-xinit
      - xorg-twm
      - i3-wm
      - i3lock
      - i3status
  become: true
  tags:
    - wm

- name: install lightdm
  pacman:
    name:
      - lightdm
  become: true
  tags:
    - wm

- name: install utility tools
  pacman:
    name:
      - rofi
      - dunst
      - pulseaudio
      - xfce4-settings
      - xfce4-screenshooter
      - xfconf
      - ranger
      - thunar
  become: true
  tags:
    - wm

- name: install default graphic drivers
  pacman:
    name:
      - xf86-video-fbdev
      - xf86-video-vesa
  become: true
  tags:
    - wm

- name: install default graphic drivers
  pacman:
    name:
      - xf86-video-fbdev
      - xf86-video-vesa
  become: true
  tags:
    - wm    

- name: Copy .xintrc to home directroy
  copy:
    dest: ~/.xincattrc
    content: |
      setxbmap de
      exec i3
    mode: 0640
    force: no
  tags:
    - wm