---
- name: install i3
  pacman:
    name:
      - xorg
      - xorg-xinit
      - xorg-twm
      - i3-wm
      - i3lock
      - i3status
  become: true
  tags:
    - wm

- name: install lightdm
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
  become: true
  tags:
    - wm

- name: install utility tools
  pacman:
    name:
      - rofi
      - dunst
      - pulseaudio
      - xfce4-settings
      - xfce4-screenshooter
      - xfconf
      - ranger
      - thunar
      - thunar-archive-plugin
      - gnome-calculator
  become: true
  tags:
    - wm

- name: install fonts
  pacman:
    name:
      - ttf-jetbrains-mono
      - cantarell-fonts
      - gnu-free-fonts
      - ttf-dejavu
      - noto-fonts
  become: true
  tags:
    - wm

- name: install default graphic drivers
  pacman:
    name:
      - xf86-video-fbdev
      - xf86-video-vesa
  become: true
  tags:
    - wm

- name: install terminal
  pacman:
    name:
      - gnome-terminal
      - xterm
  become: true
  tags:
    - wm

- name: adding existing user to some multimedia unix groups
  user:
    name: "{{ username }}"
    groups:
      - power
      - audio
      - storage
    append: yes
  become: yes

- name: Copy .xintrc to home directroy
  copy:
    dest: ~/.xincattrc
    content: |
      setxbmap de
      exec i3
    mode: 0640
    force: no
  tags:
    - wm

- name: enable ligthdm service
  service:
    name: lightdm
    enabled: yes
    state: started
  become: yes

- name: Install fonts
  community.general.pacman:
    name: 
      - ttf-google-fonts-git
      - ttf-jetbrains-mono
      - ttf-ms-fonts
      - nerd-fonts-dejavu-complete
    state: present
    executable: yay

- name: Install theme
  community.general.pacman:
    name: 
      - arc-icon-theme-git
    state: present
    executable: yay