---
- name: Install i3
  pacman:
    name:
      - xorg
      - xorg-xinit
      - xorg-twm
      - i3-gaps
      - i3lock
      - i3status
      - i3blocks
      - upower
      - xautolock
      - xsettingsd
  become: true
  tags:
    - wm

- name: Install lightdm
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
  become: true
  tags:
    - wm

- name: Install utility tools
  pacman:
    name:
      - rofi
      - dunst
      - pulseaudio
      - xfce4-settings
      - xfce4-screenshooter
      - xfconf
      - thunar
      - thunar-archive-plugin
      - xarchiver
      - qalculate-gtk
  become: true
  tags:
    - wm

- name: Install fonts
  pacman:
    name:
      - ttf-jetbrains-mono
      - cantarell-fonts
      - gnu-free-fonts
      - ttf-dejavu
      - noto-fonts
  become: true
  tags:
    - wm

- name: Install default graphic drivers
  pacman:
    name:
      - xf86-video-fbdev
      - xf86-video-vesa
  become: true
  tags:
    - wm

- name: Install terminal
  pacman:
    name:
      - gnome-terminal
      - xterm
  become: true
  tags:
    - wm

- name: Adding existing user to some multimedia unix groups
  user:
    name: "{{ username }}"
    groups:
      - power
      - audio
      - storage
    append: true
  become: true
  tags:
    - wm
    - permission

- name: Copy .xintrc to home directroy
  copy:
    dest: ~/.xincattrc
    content: |
      setxbmap de
      exec i3
    mode: "0640"
    force: false
  tags:
    - wm

- name: Enable ligthdm service
  service:
    name: lightdm
    enabled: true
  become: true
  tags:
    - wm
    - systemd
