---
- name: install i3
  pacman:
    name:
      - xorg
      - i3-wm
      - i3lock
      - i3status
  become: true
  tags:
    - wm

- name: install lightdm
  pacman:
    name:
      - lightdm
  become: true
  tags:
    - wm

- name: install utility tools
  pacman:
    name:
      - rofi
      - dunst
      - pulseaudio
      - xfce4-settings
      - xfce4-screenshooter
      - xfconf
      - ranger
      - thunar
  become: true
  tags:
    - wm
