---
- name: install i3
  pacman:
    name:
      - xorg
      - xorg-xinit
      - xorg-twm
      - i3-gaps
      - i3lock
      - i3status
      - i3blocks
  become: true
  tags:
    - wm

- name: install lightdm
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
  become: true
  tags:
    - wm

- name: install utility tools
  pacman:
    name:
      - rofi
      - dunst
      - pulseaudio
      - xfce4-settings
      - xfce4-screenshooter
      - xfconf
      - ranger
      - thunar
      - thunar-archive-plugin
      - xarchiver
      - qalculate-gtk
  become: true
  tags:
    - wm

- name: install fonts
  pacman:
    name:
      - ttf-jetbrains-mono
      - cantarell-fonts
      - gnu-free-fonts
      - ttf-dejavu
      - noto-fonts
  become: true
  tags:
    - wm

- name: install default graphic drivers
  pacman:
    name:
      - xf86-video-fbdev
      - xf86-video-vesa
  become: true
  tags:
    - wm

- name: install terminal
  pacman:
    name:
      - gnome-terminal
      - xterm
  become: true
  tags:
    - wm

- name: adding existing user to some multimedia unix groups
  user:
    name: "{{ username }}"
    groups:
      - power
      - audio
      - storage
    append: true
  become: true
  tags:
    - wm
    - permission

- name: Copy .xintrc to home directroy
  copy:
    dest: ~/.xincattrc
    content: |
      setxbmap de
      exec i3
    mode: 0640
    force: false
  tags:
    - wm

- name: enable ligthdm service
  service:
    name: lightdm
    enabled: true
    state: started
  become: true
  tags:
    - wm

- name: Install fonts
  community.general.pacman:
    name:
      - ttf-google-fonts-git
      - ttf-jetbrains-mono
    state: present
    executable: yay
    extra_args: --noconfirm
  tags:
    - wm
    - yay

- name: Install theme
  community.general.pacman:
    name:
      - arc-icon-theme-git
    state: present
    executable: yay
    extra_args: --noconfirm
  tags:
    - wm
    - yay
