---
- name: Update pacman cache
  pacman:
    update_cache: true
  become: true

- name: Install pacman tools
  pacman:
    name: pacman-contrib
  become: true

- name: Install reflector
  pacman:
    name: reflector
  become: true

# - name: update pacman mirrorlist
#   script: update-mirrorlist.sh
#   become: true

- name: Install base metapackage
  pacman:
    name: base
  become: true

- name: Perform full upgrade
  pacman:
    upgrade: true
    update_cache: true
  become: true
