---
- name: Download rust up
  become: true
  get_url:
    url: https://sh.rustup.rs
    dest: "{{ rustup_dest }}"
    mode: "0440"
  register: download
  tags:
    - development
    - rust

- name: Change file permission of rustup.sh
  become: true
  file:
    path: "{{ rustup_dest }}"
    state: touch
    mode: u=rwx,g=rx,o=rx
  tags:
    - development
    - rust

- name: Install JDK
  pacman:
    name:
      - jdk{{ openjdk_version }}-openjdk
      - openjdk{{ openjdk_version }}-src      
      - openjdk{{ openjdk_version }}-doc
    state: present
  become: true
  tags:
    - development
    - java

- name: Install python
  pacman:
    name:
      - python3
      - python-pip
  become: true
  tags:
    - development
    - python

- name: Install nodejs
  pacman:
    name:
      - nodejs
  become: true
  tags:
    - development
    - nodejs

- name: Install go
  pacman:
    name:
      - go
  become: true
  tags:
    - development
    - go
