---
- name: Install rust
  pacman:
    name:
      - rustup
  become: true
  tags:
    - development
    - rust

- name: Install JDK
  pacman:
    name:
      - jdk{{ openjdk_version }}-openjdk
      - openjdk{{ openjdk_version }}-src
      - openjdk{{ openjdk_version }}-doc
    state: present
  become: true
  tags:
    - development
    - java

- name: Install python
  pacman:
    name:
      - python3
      - python-pip
      - python-distutils-extra
      - python-virtualenv
  become: true
  tags:
    - development
    - python

- name: Install nodejs
  pacman:
    name:
      - nodejs
  become: true
  tags:
    - development
    - nodejs

- name: Install go
  pacman:
    name:
      - go
  become: true
  tags:
    - development
    - go

- name: Install developer tools
  pacman:
    name:
      - postgresql-libs
  become: true
  tags:
    - development
