---
- name: Install Open JDK
  pacman:
    name:
      - jdk{{ openjdk_version }}-openjdk
      - openjdk{{ openjdk_version }}-src      
      - openjdk{{ openjdk_version }}-doc
    state: present
  become: true
  tags:
    - development
    - java
    - jdk
