---
- name: Install Open JDK
  pacman:
    name:
      - jdk{{ openjdk_version }}-openjdk
      - openjdk{{ openjdk_version }}-src
      - jre{{ openjdk_version }}-openjdk
      - jre{{ openjdk_version }}-openjdk-headless
    state: present
  become: true
  tags:
    - development
    - java
    - jdk
