---
- name: enable acpid services
  become: yes
  systemd:
    name: acpid
    enabled: yes

- name: enable avahi-daemon services
  become: yes
  systemd:
    name: avahi-daemon
    enabled: yes

- name: enable cups services
  become: yes
  systemd:
    name: cups
    enabled: yes