---
- name: enable acpid services
  become: true
  systemd:
    name: acpid
    enabled: true
    state: started

- name: enable avahi-daemon services
  become: true
  systemd:
    name: avahi-daemon
    enabled: true
    state: started

- name: enable cups services
  become: true
  systemd:
    name: cups
    enabled: true
    state: started
