---
- name: install base packages
  pacman:
    name:
      - vim
      - sed
      - meld
      - diffutils
      - unzip
      - zip
      - unrar
      - tar
      - coreutils
      - tree
      - man-db
      - wget
      - zip
      - tar
      - unzip
      - yq
      - jq
  become: true
  tags:
    - system

- name: Install basic developer tools
  package:
    name:
      - git
      - tig
      - base-devel
  become: true
  tags:
    - system
    - development

- name: Install utility tools
  package:
    name:
      - keepass
  become: true
  tags:
    - system

- name: Install web tools
  package:
    name:
      - httpie
      - firefox
      - chromium
      - mutt
  become: true
  tags:
    - system
    - network

- name: Install network tools
  package:
    name:
      - networkmanager
      - openssl
      - openvpn
      - remmina
      - wireshark-qt
      - tcpdump
      - gnu-netcat
      - iftop
      - iwd
      - dialog
  become: true
  tags:
    - system
    - network

- name: Install update systemd resolver
  command: yay -S --noconfirm {{ item }}
  with_items:
    - aur/openvpn-update-systemd-resolved
  tags:
    - system
    - network
    - yay

- name: Install nis tools
  command: yay -S --noconfirm {{ item }}
  with_items:
    - autofs
    - ypbind-mt
    - yp-tools
  tags:
    - system
    - nis
    - yay
