---
- name: Install base packages
  pacman:
    name:
      - vim
      - sed
      - meld
      - diffutils
      - unzip
      - zip
      - unrar
      - tar
      - coreutils
      - tree
      - man-db
      - wget
      - zip
      - tar
      - unzip
      - yq
      - jq
      - ntp
      - bat
      - direnv
      - htop
      - dmidecode
      - fzf
      - acpid
      - dbus
      - avahi
      - cups
      - bluez
      - bluez-utils
      - openssh
      - dhcpcd
      - sudo
      - fwupd
      - udisks2
      - lshw
  become: true
  tags:
    - system

- name: Install basic developer tools
  package:
    name:
      - git
      - tig
      - base-devel
  become: true
  tags:
    - system
    - development

- name: Install password tools
  command: yay -S --needed --noconfirm {{ item }}
  with_items:
    - keepass
    - 1password
    - 1password-cli
  tags:
    - system
    - yay

- name: Install web tools
  package:
    name:
      - httpie
      - firefox
      - chromium
      - mutt
  become: true
  tags:
    - system

- name: Install network tools
  package:
    name:
      - networkmanager
      - netctl
      - openssl
      - openvpn
      - remmina
      - wireshark-qt
      - tcpdump
      - gnu-netcat
      - iftop
      - iwd
      - dialog
      - wpa_supplicant
      - iw
      - ufw
      - gufw
  become: true
  tags:
    - system
    - network

- name: Install update systemd resolver
  command: yay -S --needed --noconfirm {{ item }}
  with_items:
    - aur/openvpn-update-systemd-resolved
  tags:
    - system
    - network
    - yay

- name: Install nis tools
  command: yay -S --needed --noconfirm {{ item }}
  with_items:
    - ypbind-mt
    - yp-tools
  tags:
    - system
    - nis
    - yay

- name: Install office tools
  pacman:
    name:
      - gimp
      - galculator
      - cups
      - cups-pdf
      - mupdf
      - qpdf
      - xfce4-screenshooter
      - extra/mattermost-desktop
  become: true
  tags:
    - office
    - system

- name: Install spotify
  command: yay -S --needed --noconfirm {{ item }}
  with_items:
    - spotify
  tags:
    - yay
    - system

- name: Install terminal tools
  pacman:
    name:
      - ranger
      - tree
  become: true
  tags:
    - system

- name: Add calculator link
  file:
    src: "/usr/bin/galculator"
    dest: "/usr/bin/calculator"
    owner: "{{ username }}"
    group: "{{ usergroup }}"
    state: link
  become: true
  tags:
    - system

- name: Install docking station packages
  pacman:
    name:
      - bolt
  become: true
  tags:
    - system

- name: Install sound packages
  pacman:
    name:
      - pamixer
      - pulseaudio
      - pulseaudio-alsa
      - alsa-utils
      - pavucontrol
  become: true
  tags:
    - system

- name: Install printer driver and tools
  command: yay -S --needed --noconfirm {{ item }}
  with_items:
    - hplip
  tags:
    - system
    - yay

- name: Adding user to group sys
  user:
    name: "{{ username }}"
    groups: sys
    append: true
  become: true
  tags:
    - system

- name: Adding user to group lp
  user:
    name: "{{ username }}"
    groups: lp
    append: true
  become: true
  tags:
    - system
