---
- name: install base packages
  pacman:
    name:
      - vim
      - meld
      - diffutils
      - unzip
      - zip
      - unrar
      - tar
      - coreutils
      - tree
      - man-db
  become: true
  tags:
    - system

- name: Install basic developer tools
  package:
    name:
      - git
      - tig
      - base-devel
  become: true
  tags:
    - system
    - development

- name: Install utility tools
  package:
    name:
      - keepass
  become: true
  tags:
    - system

- name: Install web tools
  package:
    name:
      - httpie
      - firefox
      - chromium
      - mutt
  become: true
  tags:
    - system
    - network

- name: Install network tools
  package:
    name:
      - networkmanager
      - openssl
      - openvpn
      - remmina
      - wireshark-qt
      - tcpdump
      - gnu-netcat
      - iftop
      - iwd
  become: true
  tags:
    - system
    - network

- name: Install nis tools
  community.general.pacman:
    name:
      - autofs
      - ypbind-mt
      - yp-tools
    state: present
    executable: yay
  tags:
    - system
    - nis
    - yay
