---
- name: install sound packages
  pacman:
    name:
      - pamixer
      - pulseaudio
      - pulseaudio-alsa
      - alsa-utils
      - pavucontrol
  become: true
  tags:
    - sound

- name: install spotify
  command: yay -S --noconfirm {{ item }}
  with_items:
    - spotify
  tags:
    - yay
