---
- name: install sound packages
  pacman:
    name:
      - pamixer
      - pulseaudio
      - pulseaudio-alsa
      - alsa-utils
      - pavucontrol
  become: true
  tags:
    - sound

- name: install spotify
  community.general.pacman:
    name:
      - spotify
    state: present
    executable: yay
  tags:
    - yay
