name: check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3

      - name: lint
        uses: ansible/ansible-lint-action@main
        with:
          targets: "site.yml"

      # see https://github.com/roles-ansible/check-ansible-archlinux-latest-action/issues/5
      # - name: ansible check with archlinux:latest
      #   uses: roles-ansible/check-ansible-archlinux-latest-action@master
      #   with:
      #     targets: "site.yml"
      #     group: "github"
      #     hosts: "localhost"
      #     requirements: requirements.yml
      #     tags: "yay,dotfiles"
