name: Install

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3

      - name: Set environment variables
        run: export "ENVIRONMENT=github"

      - name: ansible check with archlinux:latest
        uses: roles-ansible/check-ansible-archlinux-latest-action@master
        with:
          targets: "site.yml"
          group: "github"
          hosts: "localhost"
          requirements: requirements.yml
          skiptags: "yay,systemd"
